query GetElections($where: ElectionRoundWhereInput, $orderBy: [ElectionRoundOrderByInput!], $offset: Int, $limit: Int) {
  electionRounds(where: $where, orderBy: $orderBy, offset: $offset, limit: $limit) {
    ...ElectionRoundFields
    __typename
  }
}
fragment ElectionRoundFields on ElectionRound {
  id
  cycleId
  endedAtBlock
  endedAtTime
  endedAtNetwork
  candidates {
    stake
  }
  castVotes {
    voteForId
  }
}
