query GetNftIssuedCount($where: NftIssuedEventWhereInput) {
  nftIssuedEventsConnection(where: $where) {
    totalCount
  }
}
query GetNftSaleCount($where: NftBoughtEventWhereInput) {
  nftBoughtEventsConnection(where: $where) {
    totalCount
  }
}
