query GetForumPostsCount($where: ForumPostWhereInput) {
  forumPostsConnection(first: 0, where: $where) {
    totalCount
  },
  
  forumPosts{
    createdAt
    author{
      handle
    }
    text    
  }
}
