

query GetVideos($where:VideoWhereInput){
  videos(orderBy: createdAt_DESC, where: $where) {
    createdAt
    description
    id
    title
    media {
      id
    }
    channel {
      id
      title
      ownerMember {
        handle
        id
      }
    }
  }
}
