

query GetVideos($where:VideoWhereInput, $limit:Int){
  videos(orderBy: createdAt_DESC, where: $where, limit:$limit) {
    createdAt
    description
    id
    title
    media {
      id
    }
    channel {
      id
      title
      ownerMember {
        handle
        id
      }
    }
  }
}
